#!/usr/bin/env zsh
# checkMach/checkMach

# checkMach
# Check the security properties of Mach-O executables
declare -r CHECKMACH_VERSION="v0.1.0"

set -euo pipefail
# -e exit if any command returns non-zero status code
# -u prevent using undefined variables
# -o pipefail force pipelines to fail on first non-zero status code

IFS=$'\n\t'
# Set Internal Field Separator to newlines and tabs
# This makes bash consider newlines and tabs as separating words
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode/

### Define Colours ###
tput sgr0; 
# reset colors
readonly RESET=$(tput sgr0);
readonly BOLD=$(tput bold);
readonly RED=$(tput setaf 1);
### END Colours ###

function usage {

  echo -e "\\nCheck the security properties of a Mach-O executable\\n"
  echo -e "  Usage: ./checkMach /path/to/macho/binary\\n"

  exit 0
}


### Utility Functions ###
# macos_compatability_check
# get_codesign_flags
# get_codesign_bitmask

function macos_compatability_check {
  
  local os
  os="$(uname -s)"

  if [[ "${os}" != "Darwin" ]]; then 
    echo "[❌] This script was written for macOS"
    exit 1
  fi
}


function get_codesign_flags {
  # get_codesign_flags
  #   Executes codesign on a binary
  #   Parses comma seperated list of flags into an array
  local -r binary_path=${1:?No parameters passed to get_codesign_flags}
  local codesign_flags
  # declare -a flags

  codesign_flags=$(codesign --display --verbose "${binary_path}" 2>&1 \
          | awk 'FNR == 4 {print $4}' \
          | awk -F '[(|)]' '{print $2}')
  
  local IFS=,
  # Set IFS to comma (,)
  read -ra flags <<< "${codesign_flags}"
  # Reads contents of $codesign_flags into array $flags
}


function get_codesign_bitmask {

  bitmask=$(codesign --display --verbose "${binary_path}" 2>&1 \
          | awk 'FNR == 4 {print $4}' \
          | awk -F '[=|(]' '{print $2}')
}


### END UTILITY FUNCTIONS ###


function check_aslr {

  if /usr/bin/otool -hv "${1}" | grep -q 'PIE'; then
    echo "ASLR/ PIE: ✅"
  else
    echo "ASLR/ PIE: ❌"
  fi
}


############################ 


function main {

  macos_compatability_check
  # Check the system is running macOS 

  local -r binary_path=${1:-"usage"}
  declare -a flags
  declare bitmask

  trap ctrl_c SIGINT
  # Detect and react to the user hitting CTRL + C

  if [[ "${binary_path}" == "usage" ]]; then
    usage
  fi

  check_aslr "${binary_path}"
}

main "$@"
